version: '3'
services:
  mosquitto:
    build: ./
    image: tranvietanh1991/mosquitto:1.4.11-alpine
#    image: eclipse-mosquitto:1.4.8
    volumes:
      - ./conf:/mosquitto/config
    sysctls:
      net.core.somaxconn: 4096
#      net.ipv4.tcp_syncookies: 0
#      net.ipv4.tcp_mesm: "786432 1697152 1945728"
#      net.ipv4.tcp_rmem: "4096 4096 16777216"
#      net.ipv4.tcp_wmem: "4096 4096 16777216"
#      net.ipv4.ip_local_port_range: "1000 65535"
    ulimits:
      nproc: 65535
      nofile: 65535
    ports:
      - 1883:1883
      - 15675:15675
      - 9001:9001