FROM debian:latest
MAINTAINER tranvietanh1991

RUN apt-get update
RUN apt-get install -y python python-pip python-dev libxml2-dev libxslt-dev libffi-dev libssl-dev zsh
RUN pip install lxml && pip install pyopenssl && pip install Scrapy
