---
version: '2'
services:
  elk:
    image: sebp/elk
    ports:
      - "5601:5601" #kibana
      - "9200:9200" #elasticsearch JSON interface
      - "5044:5044" #logstash beats
#      - "9300:9300" #elasticsearch transport interface
    volumes:
      - ./logstash/conf.d/:/etc/logstash/conf.d/ #logstash config
      - ./elasticsearch/templates/:/etc/elasticsearch/templates/ #ES index templates