
ansible_tower:
  container_name: ansible-tower
  build: .
  command: bash
  stdin_open: true #allow terminal so that we can use container as a tranditional VM
  tty: true #allow terminal so that we can use container as a tranditional VM
  ports:
    - "80:80"
    - "443:443"
    - "8080:8080"
  links:
    - postgres
postgres:
  image: postgres
  environment:
    POSTGRES_USER: admin
    POSTGRES_PASSWORD: admin